name: client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

scripts: derry.yaml

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 多言語対応
  flutter_localizations:
    sdk: flutter
  # アニメーション
  lottie: ^3.3.1
  # ログ用
  logger: ^2.5.0
  # 配列をいい感じに拡張してくれるやつ
  collection: ^1.19.1
  # 画面遷移用
  go_router: ^14.8.1
  # スプラッシュ画面をいい感じに作ってくれるやつ
  flutter_native_splash: ^2.4.5
  # アプリアイコンをいい感じに作ってくれるやつ
  flutter_launcher_icons: ^0.14.3
  # iOSだと数字入力キーボードがデフォルトで閉じれないらしいので入れている
  keyboard_actions: ^4.2.0
  # スマホ端末にデータを保存する
  shared_preferences: ^2.5.2
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.31
  path_provider: ^2.1.5
  path: ^1.9.1
  # 状態管理
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # ローカル端末通知
  flutter_local_notifications: ^19.0.0
  # DB定義参照用
  drift_db_viewer: ^2.1.0
  common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  go_router_builder: ^2.8.2
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  drift_dev: ^2.26.0

flutter:
  uses-material-design: true
