// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_crTQRtAnAu6RS32QVae9cggjr0NOeA',
    appId: '1:853610775142:web:7532dd2a865af7249e63a7',
    messagingSenderId: '853610775142',
    projectId: 'poker-12a1b',
    authDomain: 'poker-12a1b.firebaseapp.com',
    storageBucket: 'poker-12a1b.firebasestorage.app',
    measurementId: 'G-QQBRLKHF2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcEEcpJDVBQ2ghBWlf15VmoVM2xUTHk0Y',
    appId: '1:853610775142:android:944e2852bfb9f7cb9e63a7',
    messagingSenderId: '853610775142',
    projectId: 'poker-12a1b',
    storageBucket: 'poker-12a1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIb0kAhqgtpOnpd1UvA9ebjkfbd_3IKc',
    appId: '1:853610775142:ios:cdf2148815b080769e63a7',
    messagingSenderId: '853610775142',
    projectId: 'poker-12a1b',
    storageBucket: 'poker-12a1b.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGIb0kAhqgtpOnpd1UvA9ebjkfbd_3IKc',
    appId: '1:853610775142:ios:cdf2148815b080769e63a7',
    messagingSenderId: '853610775142',
    projectId: 'poker-12a1b',
    storageBucket: 'poker-12a1b.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq_crTQRtAnAu6RS32QVae9cggjr0NOeA',
    appId: '1:853610775142:web:84ca3c4564648ccb9e63a7',
    messagingSenderId: '853610775142',
    projectId: 'poker-12a1b',
    authDomain: 'poker-12a1b.firebaseapp.com',
    storageBucket: 'poker-12a1b.firebasestorage.app',
    measurementId: 'G-98X77S4EH9',
  );
}
